# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Chocolatey CLI'
description: 'Wrapper for the Chocolatey CLI to build and publish packages'
author: 'crazy-max'
branding:
  color: 'blue'
  icon: 'terminal'

inputs:
  args:
    description: 'Arguments to pass to Chocolatey CLI'
    required: true

runs:
  using: 'node12'
  main: 'lib/main.js'
