name: test

on:
  push:
    branches:
      - master

jobs:
  choco:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: Choco help
        uses: crazy-max/ghaction-chocolatey@master
        with:
          args: -h
